sf-to-gcp-pubsub/force-app/main/default/objects/Integration__c/Integration__c.object-meta.xml
<CustomObject>
    <description>Objeto utilizado para registar eventos de integrações.</description>
    <label>Integration</label>
    <nameField>
        <displayFormat>ID-{0000}</displayFormat>
        <label>Integration Event ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integration</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sf-to-gcp-pubsub/force-app/main/default/objects/Integration__c/fields/ExternalKey__c.field-meta.xml
<CustomField>
    <fullName>ExternalKey__c</fullName>
    <externalId>true</externalId>
    <label>External key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sf-to-gcp-pubsub/force-app/main/default/objects/Integration__c/fields/RecordId__c.field-meta.xml
<CustomField>
    <fullName>RecordId__c</fullName>
    <label>Salesforce RecordId</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

sf-to-gcp-pubsub/force-app/main/default/objects/Integration__c/fields/RequestBody__c.field-meta.xml
<CustomField>
    <fullName>RequestBody__c</fullName>
    <label>Request Body</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

sf-to-gcp-pubsub/force-app/main/default/objects/Integration__c/fields/ResponseBody__c.field-meta.xml
<CustomField>
    <fullName>ResponseBody__c</fullName>
    <label>Response Body</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

sf-to-gcp-pubsub/force-app/main/default/objects/Integration__c/fields/SalesforceObject__c.field-meta.xml
<CustomField>
    <fullName>SalesforceObject__c</fullName>
    <label>Salesforce object</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

sf-to-gcp-pubsub/force-app/main/default/objects/Integration__c/fields/StatusCode__c.field-meta.xml
<CustomField>
    <fullName>StatusCode__c</fullName>
    <label>StatusCode</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sf-to-gcp-pubsub/force-app/main/default/classes/IntegrationObjectHelperTest.cls
/***
* @author: Olavo Alexandrino <oalexandrino@gmail.com>
* data: 11/03/2022
*/	
@isTest
public with sharing class IntegrationObjectHelperTest 
{
    /***
    * @author: Olavo Alexandrino <oalexandrino@gmail.com>
    * data: 11/03/2022
    */	
    @isTest    
    static void testcreateIntegrationSobject() 
    {
        Lead objLead = new Lead();
        objLead.FirstName = 'Olavo';
        objLead.LastName = 'Alexandrino';
        objLead.Email = 'oalexandrino@gmail.com';
        objLead.Street = 'Rua ABC, 10';
        objLead.Company = objLead.FirstName + ' ' + objLead.LastName ;
        insert objLead;

        Map<String,String> dataObject   = new Map<String,String>();
        dataObject.put('StatusCode', '200');
        dataObject.put('Status', 'OK');
        dataObject.put('RequestBody', '{body}');
        dataObject.put('ResponseBody', '{response}');
        dataObject.put('ExternalKey', 'external_key');
        dataObject.put('RecordId', objLead.Id);
        dataObject.put('SalesforceObject', 'Lead');
        IntegrationObjectHelper.createIntegrationSobject(dataObject);  
        
        Integration__c objIntegration = [
                SELECT Status__c, StatusCode__c, RequestBody__c, ResponseBody__c, SalesforceObject__c, RecordId__c, ExternalKey__c
                FROM Integration__c Limit 1
        ];

        System.assertEquals(dataObject.get('Status'), objIntegration.Status__c, 'It must be equals to: ' + dataObject.get('Status'));
        System.assertEquals(dataObject.get('StatusCode'), String.valueOf(objIntegration.StatusCode__c) , 'It must be equals to: ' + dataObject.get('StatusCode'));
        System.assertEquals(dataObject.get('RequestBody'), objIntegration.RequestBody__c, 'It must be equals to: ' + dataObject.get('RequestBody'));
        System.assertEquals(dataObject.get('ResponseBody'), objIntegration.ResponseBody__c, 'It must be equals to: ' + dataObject.get('ResponseBody'));
        System.assertEquals(dataObject.get('ExternalKey'), objIntegration.ExternalKey__c, 'It must be equals to: ' + dataObject.get('ExternalKey'));
        System.assertEquals(dataObject.get('RecordId'), objIntegration.RecordId__c, 'It must be equals to: ' + dataObject.get('RecordId'));
        System.assertEquals(dataObject.get('SalesforceObject'), objIntegration.SalesforceObject__c, 'It must be equals to: ' + dataObject.get('SalesforceObject'));
    }
}