sf-to-gcp-pubsub/force-app/main/default/objects/Integration__c/Integration__c.object-meta.xml
<CustomObject>
    <description>Objeto utilizado para registar eventos de integrações.</description>
    <label>Integration</label>
    <nameField>
        <displayFormat>ID-{0000}</displayFormat>
        <label>Integration Event ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integration</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sf-to-gcp-pubsub/force-app/main/default/objects/Integration__c/fields/ExternalKey__c.field-meta.xml
<CustomField>
    <fullName>ExternalKey__c</fullName>
    <externalId>true</externalId>
    <label>External key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sf-to-gcp-pubsub/force-app/main/default/objects/Integration__c/fields/IntegrationEventName__c.field-meta.xml
<CustomField>
    <fullName>IntegrationEventName__c</fullName>
    <label>Integration event name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

sf-to-gcp-pubsub/force-app/main/default/objects/Integration__c/fields/IntegrationName__c.field-meta.xml
<CustomField>
    <fullName>IntegrationName__c</fullName>
    <description>Nome da integração (ou nome do sistema externo)</description>
    <inlineHelpText>Nome da integração (ou nome do sistema externo)</inlineHelpText>
    <label>Integration name</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

sf-to-gcp-pubsub/force-app/main/default/objects/Integration__c/fields/RecordId__c.field-meta.xml
<CustomField>
    <fullName>RecordId__c</fullName>
    <label>Salesforce RecordId</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

sf-to-gcp-pubsub/force-app/main/default/objects/Integration__c/fields/RequestBody__c.field-meta.xml
<CustomField>
    <fullName>RequestBody__c</fullName>
    <label>Request Body</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

sf-to-gcp-pubsub/force-app/main/default/objects/Integration__c/fields/ResponseBody__c.field-meta.xml
<CustomField>
    <fullName>ResponseBody__c</fullName>
    <label>Response Body</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

sf-to-gcp-pubsub/force-app/main/default/objects/Integration__c/fields/SalesforceObject__c.field-meta.xml
<CustomField>
    <fullName>SalesforceObject__c</fullName>
    <label>Salesforce object</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

sf-to-gcp-pubsub/force-app/main/default/objects/Integration__c/fields/SerializedRequestBody__c.field-meta.xml
<CustomField>
    <fullName>SerializedRequestBody__c</fullName>
    <label>Serialized Request Body</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

sf-to-gcp-pubsub/force-app/main/default/objects/Integration__c/fields/StatusCode__c.field-meta.xml
<CustomField>
    <fullName>StatusCode__c</fullName>
    <label>StatusCode</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sf-to-gcp-pubsub/force-app/main/default/classes/IntegrationObjectHelper.cls
/***
* @author: Olavo Alexandrino <oalexandrino@gmail.com>
* data: 10/03/2022
*/	
public with sharing class IntegrationObjectHelper 
{
    /***
    * @author: Olavo Alexandrino <oalexandrino@gmail.com>
    * data: 10/03/2022
    */    
    public static Integration__c createIntegrationSobject(Map<String,String> dataObject)
    {
        Integration__c objIntegration = new Integration__c();
        objIntegration.Status__c           = dataObject.get('Status');
        if (dataObject.get('StatusCode') != null ) 
        {
            objIntegration.StatusCode__c   = Decimal.valueOf(dataObject.get('StatusCode'));
        }
        objIntegration.RequestBody__c           = dataObject.get('RequestBody');
        objIntegration.SerializedRequestBody__c = dataObject.get('SerializedRequestBody');
        objIntegration.ResponseBody__c          = dataObject.get('ResponseBody');
        objIntegration.SalesforceObject__c      = dataObject.get('SalesforceObject');
        objIntegration.RecordId__c		        = dataObject.get('RecordId');        
        objIntegration.ExternalKey__c           = (dataObject.get('ExternalKey') == null) ? '' : dataObject.get('ExternalKey');
        objIntegration.IntegrationName__c		= dataObject.get('IntegrationName');        
        objIntegration.IntegrationEventName__c	= dataObject.get('IntegrationEventName');        

        insert objIntegration;

        System.debug('IntegrationSobject was created...');

        return objIntegration;
    }
}